// CONSTRUIR UMA ESCADA DE 5 DEGRAUS NO CONSOLE
// O MATERIAL DEVE SER #

// #
// ##
// ###
// ####
// #####

// CONSTRUIR UMS ESCADA COM O MATERIAL QUE O USUARIO QUISER E QUANTOS DEGRAUS ELE QUISER

// DICAS: TEM QUE USAR LAÇO
// FOR NORMAL É MAIS FÁCIL DE USAR NESSE CASO
// USAR E PESQUISA +=
// O QUE ACONTECE SE EU DEFINIR UMA VARIAVEL COM STRING VAZIA? EXEMPLO: VAR X = ""
